### ISSUE TITLE
Word spacing problem in LibreOffice 4.0.3.3 Ubuntu 13.04 with SutonnMJ font and other Unicode fonts

### ISSUE THREAD

**Issue by maateen** [maateen/avro#42]
<a href="https://github.com/FaisalHaq"><img src="https://avatars.githubusercontent.com/u/4443770?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [FaisalHaq](https://github.com/FaisalHaq)**
_Thursday May 16, 2013 at 05:24 GMT_
_Originally opened as https://github.com/sarim/ibus-avro/issues/43_

---

If I continue to type Bangla with iBus>Bengali-Avro Phonetic, no matter what the bangla font is (Except AdorsoLipi), after a while it will create a problem. The spacing between words are not correct.

Another problem is, after finishing editing, if I open this document in Windows 7 with MS Office 2003 (for printing) the words all appear as square. But no problem with PDF version.

This document is actually form windows and I need to edit it in LibreOffice in Ubuntu 13.04.

I've attached a document, just go through the words and you will notice the problem.
Download Attachment below
https://bugs.freedesktop.org/attachment.cgi?id=79235

![spacing prob](https://f.cloud.github.com/assets/4443770/510742/b42d5552-bde8-11e2-830e-917d88ff5a32.jpeg)
The font is SutonnyMJ

My PC:
Ubuntu 13.04 (32Bit)
LibreOffice 4.0.3.3

We're also discussing about it here you may have a look

http://ask.libreoffice.org/en/question/17417/word-spacing-problem-in-libreoffice-4033-ubuntu/
https://bugs.freedesktop.org/show_bug.cgi?id=64526
##

**Comment by ugcoder** [comment]
<a href="https://github.com/sarim"><img src="https://avatars.githubusercontent.com/u/1235888?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sarim](https://github.com/sarim)**
_Thursday May 16, 2013 at 05:34 GMT_

----

I received some complain about avro in libreoffice. I'll look into it. What you mean by spacing is not correct ? Multiple spaces are inserted instead of one ?

Actually ibus-avro has nothing to do with font rendering. Maybe you dont have necessary font installed in windows ? (i've no idea about MS office though)

Let me see a document, you attached a screenshot.

**Comment by ugcoder** [comment]
<a href="https://github.com/FaisalHaq"><img src="https://avatars.githubusercontent.com/u/4443770?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [FaisalHaq](https://github.com/FaisalHaq)**
_Thursday May 16, 2013 at 06:53 GMT_

----

Assalamualaikum,
What I ment by spacing problem is that, if I just press <kbd>Space</kbd> once it appears as though I've pressed many spaces or a tab. As you can see in the pic, there is just one <kbd>Space</kbd> but looks like many spaces. Download the attachment I provided and hopefully you will be able notice the issue.

Zazakallah Akhi.

**Comment by ugcoder** [comment]
<a href="https://github.com/sarim"><img src="https://avatars.githubusercontent.com/u/1235888?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sarim](https://github.com/sarim)**
_Thursday May 16, 2013 at 06:56 GMT_

----

I dont see any attachment, can you upload it somewhere and post the link ?

**Comment by ugcoder** [comment]
<a href="https://github.com/FaisalHaq"><img src="https://avatars.githubusercontent.com/u/4443770?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [FaisalHaq](https://github.com/FaisalHaq)**
_Thursday May 16, 2013 at 07:00 GMT_

----

Click this
https://bugs.freedesktop.org/attachment.cgi?id=79235

**Comment by ugcoder** [comment]
<a href="https://github.com/sarim"><img src="https://avatars.githubusercontent.com/u/1235888?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sarim](https://github.com/sarim)**
_Thursday May 16, 2013 at 07:02 GMT_

----

It seems like a problem with font rendering in libreoffice, have you tried Solaimanlipi ?

**Comment by ugcoder** [comment]
<a href="https://github.com/FaisalHaq"><img src="https://avatars.githubusercontent.com/u/4443770?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [FaisalHaq](https://github.com/FaisalHaq)**
_Thursday May 16, 2013 at 07:16 GMT_

----

Yes just now I tried Solaimanlipi but same problem, But AdorshoLipi works great. But using AdorshoLipi will not solve the problem, because if we edit other fonts it will create problem. We need permanent solusion regarding fonts.

**Comment by ugcoder** [comment]
<a href="https://github.com/FaisalHaq"><img src="https://avatars.githubusercontent.com/u/4443770?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [FaisalHaq](https://github.com/FaisalHaq)**
_Thursday May 16, 2013 at 07:28 GMT_

----

Sorry correction: Solaimanlipi not creating problem but automatically font changing to Lohit Hindi which causing the problem, but if I change the font to Solaimanlipi no problem, the spacing issue gets solved. But not solving the SutonnyMJ issue. Because most of the official work needs to be done in SutonnyMJ.
