### ISSUE TITLE
Problem in installing ibus-avro in Fedora 22 KDE

### ISSUE THREAD

**Issue by maateen** [maateen/avro#94]
<a href="https://github.com/redwandipto"><img src="https://avatars.githubusercontent.com/u/13656605?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [redwandipto](https://github.com/redwandipto)**
_Wednesday Aug 05, 2015 at 08:16 GMT_
_Originally opened as https://github.com/sarim/ibus-avro/issues/95_

---

I tried to install menually ibus-avro, downloading the source file and i have also installed all dependencies. But I could not find any input method for ibus-avro in my keyboard layout. 

Please, let me know if there is any solution for this problem.

Thank You
##

**Comment by ugcoder** [comment]
<a href="https://github.com/AsifulNobel"><img src="https://avatars.githubusercontent.com/u/7826129?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [AsifulNobel](https://github.com/AsifulNobel)**
_Monday Aug 24, 2015 at 22:07 GMT_

----

I had similar problem in fedora 22 xfce. I solved it by launching **im-chooser** from terminal and then I selected Ibus input in the GUI. Then I had run **ibus-setup** command from terminal to launch the GUI and had selected the preferences there. Try it, see if it helps.

**Comment by ugcoder** [comment]
<a href="https://github.com/redwandipto"><img src="https://avatars.githubusercontent.com/u/13656605?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [redwandipto](https://github.com/redwandipto)**
_Friday Aug 28, 2015 at 16:39 GMT_

----

Thank you for your suggestion. 😊 Since I am using nowadays Arch Linux and
ibus avro works fine in Arch, but I will try it when I get back into Fedora
again.
